services:
  - type: web
    name: moneymirror-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8013528707:AAHs8-1hdROjGLifIpIaUIMgRfgM_NeoEdw
