services:
  - type: web
    name: moneymirror-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8013528707:AAHs8-1hdROjGLifIpIaUIMgRfgM_NeoEdw
